### ISSUE TITLE
Error connect in Deno

### ISSUE THREAD

**Issue by ghost** [Andersgee/LinearAlgebra.wasm#1]
# Issue

Hi! 
I download **LinearAlgebra.wasm** and add simple code to connect wasm module:

```js
async function wasm(path) {
    const readWasm = await Deno.readFile(path)
    const bin = new Uint8Array(readWasm)
    const mod = new WebAssembly.Module(bin)
    const instance = new WebAssembly.Instance(mod)
    return instance.exports
}

await wasm('LinearAlgebra.wasm')
```

I test and see this error:

`WebAssembly.Instance(): Imports argument must be present and must be an object`

## Info

Deno: https://deno.land/
Using WA: https://deno.land/manual@v1.8.3/getting_started/webassembly

Thanks!

**Comment by Andersgee** [comment]
Hi!

You have to pass a few specific imports along as in the example
https://github.com/Andersgee/LinearAlgebra.wasm/blob/master/example/web/LinearAlgebra.js

**Comment by ghost** [comment]
In your example used **WebAssembly Javascript API for browser**. This working on client side, but not working on server side.
Сould you add an example for the server side?

## Example 

I compiled this AssemblyScript code in wasm.
```ts
export function add(x: i32, y: i32): i32 {
  return x + y
}
```
And i wrote a simple example for you (12 lines)
[example.zip](https://github.com/Andersgee/LinearAlgebra.wasm/files/6275301/example.zip)

**Comment by ghost** [comment]
I looked at your account, it seems you are compiling wasm from julia. I compile from assemblyScript and rust, maybe there is a difference.
Could you drop a link to the tutorial that shows how to compile from julia?

**Comment by Andersgee** [comment]
Never used deno but I installed it and made an example that works, see here: https://github.com/Andersgee/LinearAlgebra.wasm/tree/master/example/deno

**Comment by ghost** [comment]
Thank you very much! Get Lin.Alg.wasm in my backend arsenal!
